version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python src/quotes.py src/twilio.py src/weather_api.py app.py
  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python src/quotes.py src/twilio.py src/weather_api.py app.py
  deploy:
    docker:
      - image: cimg/python:3.11
    steps:
      - run: echo "Deploying to production server"

workflows:
  build_and_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build 
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main